### ISSUE TITLE
Multi-processing with strings indexes

### ISSUE THREAD

**Issue by Nathan-Furnal** [tgsmith61591/pmdarima#142]
Hi ! 

I'm running into an issue where when I try to use multiprocessing on a function that uses slices of datetimes indexes based on strings, I get errors which I don't get when using the function otherwise.

Min example :

```
import pandas as pd
import numpy as np
from pmdarima import auto_arima
from multiprocessing import Pool, cpu_count
from itertools import repeat

time_index = pd.date_range(start="2007-01",end="2017-01",freq="MS")
df = pd.DataFrame({"A":np.random.randint(0,100,121),
"B":np.random.randint(20,50,121)},index=time_index)
```

and the function is the following : 

```
def sarima_simple(series,start_date,ylen=12,seasons=6):
    
    train = series[series.index < start_date]
    
    model = auto_arima(train, start_p=1, start_q=1,
                             max_p=2, max_q=2,m=seasons,
                             start_P=0, seasonal=True,
                             d=1,D=1, trace=False,
                             error_action='ignore',  # don't want to know if an order does not work
                             suppress_warnings=True, # don't want convergence warnings
                             stepwise=True)
    
    forecast = np.round(model.predict(n_periods=ylen))
    
    return forecast

```
This function works as expected when used : 

```
output = sarima_simple(df['A'],start_date="2016-01",ylen=12,seasons=12)
print(output)
[48. 46. 52. 60. 64. 58. 48. 54. 72. 53. 51. 53.]

```

But when multiprocessing is used, the creation of "train" is problematic : 

```
pool = Pool(cpu_count())
results = pool.starmap(sarima_simple,zip(df,repeat('2016-01')))  # This line creates the error
results_final = results.get()
```
Shows this error (sorry for the long message) : 

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/nathan/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/nathan/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "<ipython-input-134-55e86ae8b370>", line 3, in sarima_simple
    train = series[series.index < start_date]
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'str'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-142-59ae77d41bb9> in <module>
      1 pool = Pool(cpu_count())
----> 2 results = pool.starmap(sarima_simple,zip(df,repeat('2016-01')))

~/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    274         `func` and (a, b) becomes func(a, b).
    275         '''
--> 276         return self._map_async(func, iterable, starmapstar, chunksize).get()
    277 
    278     def starmap_async(self, func, iterable, chunksize=None, callback=None,

~/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'str'
```

Which from understanding is due to the comparaison when I slice the series to create the training set.  Well I thought, this is not a huge problem, I will try to use ```iloc``` instead. 
Such that : 
```
idx = {j:i for (i,j) in enumerate(df.columns)}
```
and in the function body:

``` train = train.iloc[-ylen:,idx[series.name]]``` 

And we get : 

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/nathan/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/nathan/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "<ipython-input-172-b53f12fd70dd>", line 3, in sarima_simple
    train = series.iloc[:-ylen,idx[series.name]]
AttributeError: 'str' object has no attribute 'iloc'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-173-59ae77d41bb9> in <module>
      1 pool = Pool(cpu_count())
----> 2 results = pool.starmap(sarima_simple,zip(df,repeat('2016-01')))

~/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    274         `func` and (a, b) becomes func(a, b).
    275         '''
--> 276         return self._map_async(func, iterable, starmapstar, chunksize).get()
    277 
    278     def starmap_async(self, func, iterable, chunksize=None, callback=None,

~/miniconda3/envs/time-linux/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

AttributeError: 'str' object has no attribute 'iloc'
```

The series seems to be treated as a string and I don't understand why.

If anyone has a clue as to what to do, I'd be delighted!

Thanks

**Comment by tgsmith61591** [comment]
I'm not 100% sure how the whole `starmap` thing is working, but I can get this to work with `joblib`, so I'm inclined to believe that's where your problem lies...

```python
from sklearn.externals.joblib import Parallel, delayed

results = Parallel(n_jobs=-1)(
    delayed(sarima_simple)(df[series], start_date="2016-01")
    for series in ("A", "B"))

print(results)
# [array([34., 39., 46., 36., 34., 35., 34., 35., 43., 33., 31., 32.]), array([33., 32., 34., 33., 32., 34., 33., 32., 34., 33., 32., 35.])]
```

**Comment by tgsmith61591** [comment]
... and if `starmap` is your preferred approach, I got it to work:

```python
results = pool.starmap(sarima_simple, ((df["A"], '2016-01'), (df["B"], '2016-01')))
print(results)
# [array([34., 39., 46., 36., 34., 35., 34., 35., 43., 33., 31., 32.]), array([33., 32., 34., 33., 32., 34., 33., 32., 34., 33., 32., 35.])]
```

**Comment by Nathan-Furnal** [comment]
@tgsmith61591 Well that's awkward, thanks a lot for your help and your time!

**Comment by tgsmith61591** [comment]
Happens to the best of us!
