### ISSUE TITLE
Cannot install via pipenv

### ISSUE THREAD

**Issue by Tjorriemorrie** [tgsmith61591/pmdarima#164]
pipenv installation with python 3.6 fails with:
`Max retries exceeded with url: /packages/c6/ad/5e48dd6d5486db6b694eac415b52eb3b1b06c89e00721283cada147a2ae6/scipy-1.2.2-cp35-cp35m-manylinux1_i686.whl`

more:
```
$ pipenv install pmdarima
Installing pmdarima…
Adding pmdarima to Pipfile's [packages]…
Installation Succeeded
Pipfile.lock (716341) out of date, updating to (b9692e)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Locking Failed!
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python36\Lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\Lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\Lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python36\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python36\Lib\ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python36\Lib\ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "C:\Program Files\Python36\Lib\ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\adapters.py", line 445, in send
    timeout=timeout
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  [Previous line repeated 1 more times]
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pipenv.patched.notpip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/c6/ad/5e48dd6d5486db6b694eac415b52eb3b1b06c89e00721283cada147a2ae6/scipy-1.2.2-cp35-cp35m-manylinux1_i686.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 481, in actually_resolve_deps
    hashes = resolver.resolve_hashes()
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 427, in resolve_hashes
    resolved_hashes = self.resolver.resolve_hashes(self.results)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 72, in resolve_hashes
    return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 72, in <dictcomp>
    return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 473, in get_hashes
    matching_candidates) if h is not None
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 471, in <setcomp>
    return {
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 472, in <lambda>
    h for h in map(lambda c: self._hash_cache.get_hash(c.location),
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 69, in get_hash
    hash_value = self._get_file_hash(new_location) if not new_location.url.startswith("ssh") else None
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 77, in _get_file_hash
    with open_local_or_remote_file(location, self.session) as fp:
  File "C:\Program Files\Python36\Lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 531, in open_local_or_remote_file
    response = session.get(url, headers=headers, stream=True)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\download.py", line 397, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
pipenv.patched.notpip._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/c6/ad/5e48dd6d5486db6b694eac415b52eb3b1b06c89e00721283cada147a2ae6/scipy-1.2.2-cp35-cp35m-manylinux1_i686.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",))
File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python36\Lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\Lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\Lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python36\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python36\Lib\ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python36\Lib\ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "C:\Program Files\Python36\Lib\ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\adapters.py", line 445, in send
    timeout=timeout
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  [Previous line repeated 1 more times]
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pipenv.patched.notpip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/c6/ad/5e48dd6d5486db6b694eac415b52eb3b1b06c89e00721283cada147a2ae6/scipy-1.2.2-cp35-cp35m-manylinux1_i686.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/program files/python36/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 481, in actually_resolve_deps
    hashes = resolver.resolve_hashes()
  File "c:\program files\python36\lib\site-packages\pipenv\utils.py", line 427, in resolve_hashes
    resolved_hashes = self.resolver.resolve_hashes(self.results)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 72, in resolve_hashes
    return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 72, in <dictcomp>
    return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 473, in get_hashes
    matching_candidates) if h is not None
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 471, in <setcomp>
    return {
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 472, in <lambda>
    h for h in map(lambda c: self._hash_cache.get_hash(c.location),
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 69, in get_hash
    hash_value = self._get_file_hash(new_location) if not new_location.url.startswith("ssh") else None
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 77, in _get_file_hash
    with open_local_or_remote_file(location, self.session) as fp:
  File "C:\Program Files\Python36\Lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 531, in open_local_or_remote_file
    response = session.get(url, headers=headers, stream=True)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_internal\download.py", line 397, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\program files\python36\lib\site-packages\pipenv\patched\notpip\_vendor\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
pipenv.patched.notpip._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/c6/ad/5e48dd6d5486db6b694eac415b52eb3b1b06c89e00721283cada147a2ae6/scipy-1.2.2-cp35-cp35m-manylinux1_i686.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",))
```

**Comment by Tjorriemorrie** [comment]
Think it is a scipy error, apologies.
