### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

### ISSUE THREAD

**Issue by jwackito** [tgsmith61591/pmdarima#182]
After a fresh install of pmdarima:
```
pip3 install pmdarima
Requirement already satisfied: pmdarima in /usr/local/lib/python3.6/dist-packages (1.2.1)
Requirement already satisfied: scipy<1.3,>=1.2 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (1.2.1)
Requirement already satisfied: scikit-learn>=0.19 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (0.21.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (1.17.0)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (0.9.0)
Requirement already satisfied: Cython>=0.29 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (0.29.13)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (0.13.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (1.11.0)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.6/dist-packages (from pmdarima) (0.25.1)
Requirement already satisfied: patsy in /usr/local/lib/python3.6/dist-packages (from statsmodels>=0.9.0->pmdarima) (0.5.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19->pmdarima) (2.7.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19->pmdarima) (2018.5)
```
After import, I got the following error.
```
python3 -c 'import pmdarima'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pmdarima/__init__.py", line 29, in <module>
    from .arima import auto_arima, ARIMA, AutoARIMA
  File "/usr/local/lib/python3.6/dist-packages/pmdarima/arima/__init__.py", line 5, in <module>
    from .approx import *
  File "/usr/local/lib/python3.6/dist-packages/pmdarima/arima/approx.py", line 19, in <module>
    from pmdarima.arima._arima import C_Approx
  File "__init__.pxd", line 918, in init pmdarima.arima._arima
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
Not solved by downgrading numpy to other versions (I already tried 1.16, 1.15).

**Comment by jwackito** [comment]
My bad. Using an old version of numpy. Make sure np.version.version > 1.14
