### ISSUE TITLE
Could not read saved model state

### ISSUE THREAD

**Issue by jussiseppala** [tgsmith61591/pmdarima#48]
#### Description
I have problem in loading the model from file when running the code on AWS Lambda.
The issue is that everything works fine when I'm doing this on my linux but it does not work on AWS Lambda. Meaning: 

- I'm able to create the model

- I'm able to store the model as file

- I'm able to load the model from file

- I'm also able to load the model from file which is located on AWS S3 bucket

But when I deploy my code to AWS Lambda using serverless framework loading the model fails. I expect that it is related to cache folder used in pmdarima.

#### Steps/Code to Reproduce
This the code which loads the model from AWS S3 bucket.

```python
import boto3
import botocore
import os
import io
import numpy as np
from io import BytesIO
from sklearn.externals import joblib

BUCKET_NAME = 'mybcucket'

# downloads model from S3 into give file(name)
def download_model_aws(to_file_name):
	bucket = boto3.resource("s3").Bucket(BUCKET_NAME)
	with BytesIO() as modelfo:
		bucket.download_fileobj(Key=to_file_name, Fileobj=modelfo)
		model = joblib.load(modelfo)
	return model

file_name = 'forecast_models/%d-forecast.pkl' % company_id
model = download_model_aws(file_name)
```

#### Expected Results

The model should be loaded from file successfully.

#### Actual Results

Following exception is thrown:

```
Could not read saved model state from /home/myuser/.pyramid-arima-cache/2018-11-24_07-42-29.725501-000--9223363283404616476.pmdpkl. Does it still exist?: OSError
Traceback (most recent call last):
...
File "/var/task/main.py", line 46, in get_model
return download_model_aws(file_name)
File "/var/task/main.py", line 31, in download_model_aws
model = joblib.load(modelfo)
File "/var/task/sklearn/externals/joblib/numpy_pickle.py", line 568, in load
obj = _unpickle(fobj)
File "/var/task/sklearn/externals/joblib/numpy_pickle.py", line 508, in _unpickle
obj = unpickler.load()
File "/var/lang/lib/python3.6/pickle.py", line 1050, in load
dispatch[key[0]](self)
File "/var/task/sklearn/externals/joblib/numpy_pickle.py", line 328, in load_build
Unpickler.load_build(self)
File "/var/lang/lib/python3.6/pickle.py", line 1507, in load_build
setstate(state)
File "/var/task/pmdarima/arima/arima.py", line 587, in __setstate__
'Does it still exist?' % loc)
OSError: Could not read saved model state from /home/myuser/.pyramid-arima-cache/2018-11-24_07-42-29.725501-000--9223363283404616476.pmdpkl. Does it still exist?
```

#### Versions
I'm using python 3.6
My requirements.txt in serverless application looks like this:
numpy==1.14.5
scikit-learn==0.19.1
scipy==1.1.0
sklearn==0.0
pmdarima==1.0.0
statsmodels>=0.9.0
pandas==0.23.4
Cython>=0.23

**Comment by tgsmith61591** [comment]
Thanks for the well-formatted issue! 

This is tricky... I suspect I can explain why this is happening, but we might need to brainstorm an ideal solution. Unfortunately, given the [unfriendliness to pickling](https://www.alkaline-ml.com/pmdarima/serialization.html#intricacies-of-arima-serialization) of statsmodels classes, the way `pmdarima` is pickling is by separately saving the statmodels portion in the cache, and then pickling the ARIMA instance with the detached statsmodels model. When you reload the model from disk, it internally loads up the statsmodels piece from the cache.

However, since you're downloading the model pickle file from S3, I suspect the cached bit is not coming with it, which is why it breaks down when deserializing. Here are several thoughts I have:

* Allow a model whose cached statsmodels model is not present to be deserialized without raising an error, and warn only. This would allow you to separately retrieve the cached bit, load it up and bind it to the ARIMA instance. It's hacky, but it would do what you're trying. The challenge here is that an unsuspecting user will see the warning and still expect forecasting to work, though it won't before rebinding the cached model.

* Attach model parameters as attributes to the instance as it's pickled (coefficients, etc.), discarding of the (statsmodels) model state as the ARIMA is pickled, and then create a new model state from existing parameters. However, this means we're saving a much larger pickle file and puts us more at the mercy of the statsmodels API as to whether it will allow us to instantiate a model with all of the attributes we save.

Thoughts anyone (@charlesdrotar)? Whatever solution we opt for should permit the same pickling behavior so the large majority of users don't feel the impact.

**Comment by jussiseppala** [comment]
I could add one more detail to my issue: it seems that we can write to /tmp folder **only** on AWS Lambda.
So, caching is ok but we should be able to define to use only /tmp folder as a cache folder.

**Comment by jussiseppala** [comment]
As I mentioned in the original issue report I tried setting PMDARIMA_CACHE environment variable but it did not have any effect.

**Comment by tgsmith61591** [comment]
The environment variable works, but that's not where you're hitting issues. Proof:

```python
# Not set
>>> import pmdarima
>>> pmdarima._config.PMDARIMA_CACHE
'/Users/taylor.smith/.pyramid-arima-cache'
```

And here it is after setting it:

```bash
$ export PMDARIMA_CACHE=".cache"
```

```python
# After being set
>>> import pmdarima
>>> pmdarima._config.PMDARIMA_CACHE
'.cache'
```

Your problem is still what I've mentioned above. Namely, when you *fit* and *save* the model, the statsmodels artifact location is saved as an attribute. It might be beneficial for you to see some of the code. From the [pickling hook](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/arima/arima.py#L572):

```python
        # now create the full path with the cache folder
        new_loc = os.path.join(cache_loc, new_loc)

        # save the results - but only if it's fit...
        if hasattr(self, 'arima_res_'):
            # statsmodels result views work by caching metrics. If they
            # are not cached prior to pickling, we might hit issues. This is
            # a bug documented here:
            # https://github.com/statsmodels/statsmodels/issues/3290
            self.arima_res_.summary()
            self.arima_res_.save(fname=new_loc)  # , remove_data=False)

            # point to the location of the saved MLE model
            self.tmp_pkl_ = new_loc
```

When you SAVE your model, the location to the artifact is bound to the pickled file. And when you try to unpickle it, it tries to [load that model](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/arima/arima.py#L580):

```python
        # re-set the results class
        loc = state.get('tmp_pkl_', None)
        if loc is not None:
            try:
                self.arima_res_ = TimeSeriesModelResults.load(loc)
            except:  # noqa: E722
                raise OSError('Could not read saved model state from %s. '
                              'Does it still exist?' % loc)
```

Your problem is you're changing the cache location AFTER you've pickled (so all future models will be read/saved there). 

But that's not the only problem. You're downloading the pickle file from S3, so ostensibly the cached artifact exists there as well and is not getting moved over to your Lambda instance. That's the problem. And that's probably going to take more from our side to find a way to self-contain the cached model (as opposed to dropping it into a cache somewhere) so that the model is more portable.

A workaround (until this is fixed) if you're up for it would be to fit the model in a Docker container and push it to ECR (or move both the pickle and the cached state into a container, rename the cache/re-map the environment variable, whatever). Then your endpoint doesn't have to worry about moving both things over from S3.
