### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by mereldawu** [tgsmith61591/pmdarima#91]
#### Description

When importing pmdarima, an attribute error is thrown with "type object 'pmdarima.arima._arima.array' has no attribute '__reduce_cython__'"

I've installed pmdarima successfully as shown below:
```

Collecting pmdarima
  Downloading https://files.pythonhosted.org/packages/5d/94/ca83959e19556ddad833858678313dded1e956092235335bb1ca76506315/pmdarima-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (685kB)
    100% |████████████████████████████████| 686kB 8.8MB/s
Requirement already satisfied: statsmodels>=0.9.0 in /opt/conda/lib/python3.6/site-packages (from pmdarima) (0.9.0)
Requirement already satisfied: scikit-learn>=0.19 in /opt/conda/lib/python3.6/site-packages (from pmdarima) (0.20.1)
Requirement already satisfied: pandas>=0.19 in /opt/conda/lib/python3.6/site-packages (from pmdarima) (0.23.4)
Collecting Cython>=0.29 (from pmdarima)
  Downloading https://files.pythonhosted.org/packages/39/b1/2acbf92bb3c817dc99a7588a6196629a0490b3f940b672136aa4d09f91ea/Cython-0.29.2-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 1.3MB/s
Requirement already satisfied: scipy>=1.0 in /opt/conda/lib/python3.6/site-packages (from pmdarima) (1.1.0)
Requirement already satisfied: numpy>=1.10 in /opt/conda/lib/python3.6/site-packages (from pmdarima) (1.13.3)
Requirement already satisfied: pytz>=2011k in /opt/conda/lib/python3.6/site-packages (from pandas>=0.19->pmdarima) (2018.7)
Requirement already satisfied: python-dateutil>=2.5.0 in /opt/conda/lib/python3.6/site-packages (from pandas>=0.19->pmdarima) (2.7.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas>=0.19->pmdarima) (1.12.0)
Installing collected packages: Cython, pmdarima
  Found existing installation: Cython 0.28.5
    Uninstalling Cython-0.28.5:
      Successfully uninstalled Cython-0.28.5
Successfully installed Cython-0.29.2 pmdarima-1.1.0
```

#### Steps/Code to Reproduce

    from pmdarima.arima import auto_arima

#### Expected Results

Should be imported correctly.

#### Actual Results

```
AttributeError                            Traceback (most recent call last)
<ipython-input-28-d06ed12b5c16> in <module>
      1 import numpy as np
----> 2 import pmdarima

/opt/conda/lib/python3.6/site-packages/pmdarima/__init__.py in <module>
     27 
     28     # Stuff we want at top-level
---> 29     from .arima import auto_arima, ARIMA
     30     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf
     31 

/opt/conda/lib/python3.6/site-packages/pmdarima/arima/__init__.py in <module>
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      4 
----> 5 from .approx import *
      6 from .arima import *
      7 from .auto import *

/opt/conda/lib/python3.6/site-packages/pmdarima/arima/approx.py in <module>
     17 # and since the platform might name the .so file something funky (like
     18 # _arima.cpython-35m-darwin.so), import this absolutely and not relatively.
---> 19 from pmdarima.arima._arima import C_Approx
     20 
     21 __all__ = [

/opt/conda/lib/python3.6/site-packages/pmdarima/arima/_arima.cpython-36m-x86_64-linux-gnu.so in init pmdarima.arima._arima()

AttributeError: type object 'pmdarima.arima._arima.array' has no attribute '__reduce_cython__'

```

#### Versions

I'm using the [scripy-notebook image](https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile) from Jupyter's docker stack.  

The output as follows: 

```
Linux-4.9.125-linuxkit-x86_64-with-debian-buster-sid
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
NumPy 1.13.3
SciPy 1.1.0
Scikit-Learn 0.20.1
Statsmodels 0.9.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-49e09fe213db> in <module>
      6 import statsmodels; print("Statsmodels", statsmodels.__version__)
      7 
----> 8 import pmdarima; print("pmdarima", pmdarima.__version__)

/opt/conda/lib/python3.6/site-packages/pmdarima/__init__.py in <module>
     27 
     28     # Stuff we want at top-level
---> 29     from .arima import auto_arima, ARIMA
     30     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf
     31 

/opt/conda/lib/python3.6/site-packages/pmdarima/arima/__init__.py in <module>
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      4 
----> 5 from .approx import *
      6 from .arima import *
      7 from .auto import *

/opt/conda/lib/python3.6/site-packages/pmdarima/arima/approx.py in <module>
     17 # and since the platform might name the .so file something funky (like
     18 # _arima.cpython-35m-darwin.so), import this absolutely and not relatively.
---> 19 from pmdarima.arima._arima import C_Approx
     20 
     21 __all__ = [

/opt/conda/lib/python3.6/site-packages/pmdarima/arima/_arima.cpython-36m-x86_64-linux-gnu.so in init pmdarima.arima._arima()

AttributeError: type object 'pmdarima.arima._arima.array' has no attribute '__reduce_cython__'
```

**Comment by tgsmith61591** [comment]
I can (sort of ) replicate, but with a different error:

```bash
$ docker pull jupyter/scipy-notebook
$ docker run -it jupyter/scipy-notebook:latest /bin/bash
jovyan@eeb61c8a36a3:~$ python -m pip install pmdarima
jovyan@eeb61c8a36a3:~$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pmdarima
Traceback (most recent call last):
  File "__init__.pxd", line 1036, in numpy.import_array
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/__init__.py", line 29, in <module>
    from .arima import auto_arima, ARIMA
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/arima/__init__.py", line 5, in <module>
    from .approx import *
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/arima/approx.py", line 19, in <module>
    from pmdarima.arima._arima import C_Approx
  File "pmdarima/arima/_arima.pyx", line 47, in init pmdarima.arima._arima
  File "__init__.pxd", line 1038, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

I can solve it by running:

```bash
$ pip install --upgrade numpy
```

And now:

```python
>>> import numpy as np
>>> import pmdarima
>>> print(np.__version__)
>>> print(pmdarima.__version__)
1.15.4
1.1.0
```

**Comment by mereldawu** [comment]
### Issue solved by upgrading to the same numpy version. 

I get the same message previously if I don't explicitly import numpy.
Didn't think it was the numpy version, thought it had something to do with cython. 

```
root@027c82e0b01e:~# python
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pmdarima
Traceback (most recent call last):
  File "__init__.pxd", line 1036, in numpy.import_array
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/__init__.py", line 29, in <module>
    from .arima import auto_arima, ARIMA
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/arima/__init__.py", line 5, in <module>
    from .approx import *
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/arima/approx.py", line 19, in <module>
    from pmdarima.arima._arima import C_Approx
  File "pmdarima/arima/_arima.pyx", line 47, in init pmdarima.arima._arima
  File "__init__.pxd", line 1038, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
>>> import numpy as np
>>> import pmdarima
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/__init__.py", line 29, in <module>
    from .arima import auto_arima, ARIMA
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/arima/__init__.py", line 5, in <module>
    from .approx import *
  File "/opt/conda/lib/python3.6/site-packages/pmdarima/arima/approx.py", line 19, in <module>
    from pmdarima.arima._arima import C_Approx
  File "stringsource", line 105, in init pmdarima.arima._arima
AttributeError: type object 'pmdarima.arima._arima.array' has no attribute '__reduce_cython__'

```

Anyway, thanks for the library and the fast turn around time.
